  - name: config SNMP
    cisco.ios.ios_config:
      lines:
      
        - snmp-server group SUN v2c
        - snmp-server community framgia RW
        - snmp-server location "Phong Server"
        - snmp-server contact "Core Sw"

#debug
    register: vlan_output
  - debug:
        var: vlan_output.stdout_lines


